In [0]:
import numpy as np


In [0]:
# supose we have rating matrix of 5 users and 5 items, 0 value means that an user 'i' didn't  rate  an item 'j'
data = np.array([
    [3, 5, 2, 0],
    [2, 1, 0, 4],
    [1, 0, 0, 3],
    [0, 5, 0, 4],
    [0, 3, 2, 5],
])

In [0]:
num_users= data.shape[0]
num_movie=data.shape[1]
K=2       # number of factors
alpha=0.1 # learning rate parameter
beta=0.01 # regularization parameter 
iterations=20 # number of epochs 




In [0]:
#  Initialize user  feature vector
Pu = np.random.normal(scale=1./K, size=(num_users,K))
#  Initialize movie  feature vector
Qi = np.random.normal(scale=1./K, size=(num_movie,K))



In [0]:
# Initialize the biases
bu = np.zeros(num_users)
bi = np.zeros(num_movie)
b = np.mean(data[np.where(data != 0)])



In [0]:
# Create a list of training samples
samples = [(i, j, data[i, j])
  for i in range(num_users)
  for j in range(num_movie)
  if data[i, j] > 0
]

In [0]:
# training 
training = []
for i in range(iterations):
  np.random.shuffle(samples)

  # stocastic gradient decent
  for i, j, r in samples:    
    prediction = b + bu[i] + bi[j] + Pu[i, :].dot(Qi[j, :].T)
    e = (r - prediction)
    # Update biases
    bu[i] += alpha * (e - beta * bu[i])
    bi[j] += alpha * (e - beta * bi[j])

    # Update user and item latent feature matrices
    Pu[i, :] += alpha * (e * Qi[j, :] - beta * Pu[i,:])
    Qi[j, :] += alpha * (e * Pu[i, :] -beta * Qi[j,:])

  xs, ys = data.nonzero()
  predicted = b + bu[:,np.newaxis] + bi[np.newaxis:,] + Pu.dot(Qi.T)
  error = 0
  for x, y in zip(xs, ys):
    error += pow(data[x, y] - predicted[x, y], 2)
  mse=np.sqrt(error)
  training.append((i, mse))

In [9]:
# predict the missing rate 
print(predicted)

[[2.91001423 5.0007743  2.05593948 5.02169733]
 [2.00227448 1.01568748 2.16314488 3.99539966]
 [1.13416502 3.08880645 1.30773184 2.89294625]
 [2.2098558  4.97248216 1.9917281  4.04406043]
 [2.75725063 2.99897229 1.98637849 4.98399939]]


In [10]:
#mean square error
print(mse)

0.2100038788673505


In [12]:
#user vector
print(Pu)

[[-0.51617291 -0.76553397]
 [-0.36766614  0.98410921]
 [ 0.49132729 -0.48967082]
 [ 0.32480717 -0.97434251]
 [-0.96331788  0.17939071]]


In [13]:
#feature vector of the first user 
print(Pu[0])

[-0.51617291 -0.76553397]


In [14]:
#Item vector
print(Qi)

[[-0.4910988   0.13532843]
 [-0.13637223 -1.65362283]
 [ 0.39054924  0.64058257]
 [-0.83071267  0.09639309]]


In [15]:
# user bais  
print(bu)


[ 0.52300636 -0.54857836 -0.79539284  0.26410997  0.02277523]


In [16]:
#user items 
print(bi)

[-0.83980859  0.06454876 -0.85201131  1.0667687 ]
